### ISSUE TITLE
details, summary {   display: block; }

### ISSUE THREAD

**Issue by paulirish** [javan/details-element-polyfill#13]
The polyfill sets `details > summary { display: block; }`. Forcing `details` to be block seems necessary.

useragent stylesheets set block on both:
* https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/css/html.css?l=1072-1078&rcl=50e2edfb0996b46542326091721e91e3ba03a853
* https://github.com/WebKit/webkit/blob/33f8dd96b36793b2ae01c5dc6d6a697382ec3807/Source/WebCore/css/html.css#L1218-L1224

wdyt about 
```css
details, summary {   display: block; }
```

thx

**Comment by javan** [comment]
👍
