### ISSUE TITLE
Lower specifity of summary style

### ISSUE THREAD

**Issue by wesruv** [javan/details-element-polyfill#17]
First, this code is beautiful, thanks so much for making an accessible and _really_ well written polyfill. I have a quibble though, lower specificity that doesn't style unintended elements is always good, IMO.

Since `<summary>` is only meant to be a child of `<details>` or it's invalid HTML, I think we can simplify these selectors from this:
```css
details > summary::before { ... }
details[open] > summary::before { ... }
```

To this:
```css
summary::before { ... }
[open] > summary::before { ... }
```

PR incoming...

**Comment by wesruv** [comment]
https://github.com/javan/details-element-polyfill/pull/18

**Comment by wesruv** [comment]
Obviously isn't a huge deal, but it was a speed bump on when I started using this.

**Comment by javan** [comment]
> it was a speed bump on when I started using this

Just curious: How did you measure the speed difference?

**Comment by wesruv** [comment]
@javan I meant to say that it caused minor difficulty when implementing, not that it was a page performance issue. My styles that worked great on modern browsers needed adjustment to have higher specificity to work for modern browsers and the polyfill.

Speedwise CSS selectors are absurdly fast, especially since you have them in a `<style>` tag in the `<head>` 😄, so good!
