### ISSUE TITLE
Add MIT License Disclaimer to File in dist Folder

### ISSUE THREAD

**Issue by RoboticMind** [javan/details-element-polyfill#65]
Since this file is likely to be directly redistributed without including any other files, it should  probably mention that it's under MIT in the file so that others know it's MIT.  Currently it just says
`Copyright © 2019 Javan Makhmali` with no mention of MIT licensing

**Comment by nijk** [comment]
Yes, this confused me as well. @javan can you confirm that this project really is under MIT license?

**Comment by javan** [comment]
> can you confirm that this project really is under MIT license?

https://github.com/javan/details-element-polyfill/blob/844e193fac56b40ca64681ad8b80055fa60a6335/LICENSE#L1 https://github.com/javan/details-element-polyfill/blob/844e193fac56b40ca64681ad8b80055fa60a6335/package.json#L23 https://github.com/javan/details-element-polyfill/blob/844e193fac56b40ca64681ad8b80055fa60a6335/README.md#L29

<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/5355/96876047-f1629200-1445-11eb-9647-d640cf4d45c9.png"></td>
<td><img src="https://user-images.githubusercontent.com/5355/96876043-f0c9fb80-1445-11eb-98c4-37ed91e64412.png"></td>
<td><img src="https://user-images.githubusercontent.com/5355/96876048-f1629200-1445-11eb-9501-4464bed55f4a.png"></td>
</tr>
</table>
